server:
  port: 443
  servlet:
    context-path: /Shopme
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: trongtai
    key-store-password: trongtai
    
spring:
  datasource:
    password: songlong
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 888457904569-jvrc44bcpoj3bhu62hdh7ch9g38afaal.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1123340234960446
            client-secret: 1d1fdc5017ce02e6906ebe3fc4250cc8
            scope:
              - email
              - public_profile